---
- name: Install tmux
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux


- name: Place tmux.conf
  vars:
    bg_color: cyan
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
    backup: yes

